abz_task/abz_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

abz_task/employees/services/urls.py
from typing import Optional, Any

from django.http import Http404

from employees.forms import EmployeeEditForm
from employees.models import Employee
from employees.services.images import ProfilePhoto


def return_404_if_none(item: Any) -> Any:
    """Проверяет, что item есть и возвращает его, иначе вызывает 404 ошибку"""

    if not item:
        raise Http404

    return item


def get_employee_by_slug(slug: str) -> Optional[Employee]:
    """
    Возвращает работника по slug'у.

    Возвращает экземпляр класса Employee по slug'y, если такого нет,
    то возвращает None.
    """

    employee = (Employee.objects
                .select_related('position')
                .select_related('parent')
                .filter(slug=slug))

    if employee.exists():
        return employee.first()


def save_employee_from_form(form: EmployeeEditForm) -> Employee:
    """Сохраняет данные пользователя из формы"""
    
    employee = form.save()
    profile_pic = ProfilePhoto(employee.employee_photo.path)
    profile_pic.get_square_photo()
    profile_pic.save()

    return employee

abz_task/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.home, name='home'),
    path('employees_list/', views.employees_list, name='employees_list'),
    path('employee/<slug:employee_slug>/', views.employee_details, name='employee_details'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('edit_employee/<slug:employee_slug>/', views.edit_employee, name='edit_employee'),
    path('delete_photo/<int:employee_pk>/', views.delete_photo, name='delete_photo'),
    path('delete_employee/<int:employee_pk>/', views.delete_employee, name='delete_employee'),
    path('positions_list/', views.positions_list, name='positions_list'),
    path('position_details/<int:position_pk>/', views.position_details, name='position_details'),
    path('delete_position/<int:position_pk>/', views.delete_position, name='delete_position'),
    path('create_position/', views.create_position, name='create_position'),
]

abz_task/employees/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.text import slugify
from mptt.models import TreeForeignKey, MPTTModel
from unidecode import unidecode


class Position(models.Model):
    """Должность работника"""

    title = models.CharField("Должность", max_length=32)

    class Meta:
        verbose_name = "Должность"
        verbose_name_plural = "Должности"
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('employees:position_details', args=[self.pk])

    def __str__(self):
        return f"{self.title}"


class Employee(MPTTModel):
    """Работник"""

    first_name = models.CharField(
        "Имя",
        max_length=32,
    )
    second_name = models.CharField(
        "Фамилия",
        max_length=32,
    )
    patronymic = models.CharField(
        "Отчество",
        max_length=32,
    )
    slug = models.SlugField(
        "Slug",
        max_length=128,
        unique=True,
    )
    date_employment = models.DateTimeField(
        "Дата трудоустройства",
    )
    payment = models.IntegerField(
        "Зарплата",
        validators=[
            MinValueValidator(
                0,
                message="Заработная плата не может быть меньше нуля."
            )
        ],
    )
    employee_photo = models.ImageField(
        "Фото работника",
        default='photo/default.png',
        upload_to='photo/'
    )
    position = models.ForeignKey(
        Position,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Должность",
        related_name='employees',
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Начальник",
        related_name='workers'
    )

    class MTTPMeta:
        ordering_insertion_by = ['first_name', 'second_name', 'patronymic']

    class Meta:
        verbose_name = "Работник"
        verbose_name_plural = "Работники"

    def __str__(self):
        return f"{self.second_name} {self.first_name} {self.patronymic}"

    def delete(self, using=None, keep_parents=False):
        if self.get_children() and self.parent:
            self.get_children().update(parent=self.parent)
        super(Employee, self).delete(using, keep_parents)

    def save(self, *args, **kwargs):
        # Устанавливаем уникальный slug
        super(Employee, self).save(*args, **kwargs)
        (Employee.objects
         .filter(pk=self.pk)
         .update(slug=slugify(unidecode(f'{self.second_name} {self.first_name} {self.patronymic} {self.pk}')))
         )
        self.refresh_from_db(fields={'slug'})

    def get_absolute_url(self):
        return reverse('employees:employee_details', args=[self.slug])

    @property
    def full_name(self):
        return f"{self.second_name} {self.first_name} {self.patronymic}"

    @property
    def all_nodes_except_self_and_children(self):
        descendants = self.get_descendants(include_self=True).values_list('id', flat=True)
        return Employee.objects.filter(~Q(pk__in=descendants)).all()

abz_task/employees/forms.py
from django import forms

from employees.models import Employee, Position


class EditPositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = (
            'title',
        )

    def __init__(self, *args, **kwargs):
        super(EditPositionForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update(
                {
                    'class': 'form-control form-control-sm',
                    'placeholder': field.label,
                }
            )


class EmployeeEditForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = (
            'first_name',
            'second_name',
            'patronymic',
            'position',
            'parent',
            'date_employment',
            'payment',
            'employee_photo',
        )

    def __init__(self, *args, **kwargs):
        super(EmployeeEditForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update(
                {
                    'class': 'form-control form-control-sm ms-2',
                    'placeholder': field.label,
                }
            )

        self.fields['employee_photo'].widget.attrs.update({
            'class': 'form-control form-control-sm mt-2',
        })

        if self.instance.pk:
            self.fields['parent'].choices = [('', "---------")] + [
                (
                    record.pk,
                    f"{record.level * '---'} {record.full_name}",
                ) for record in self.instance.all_nodes_except_self_and_children
            ]

abz_task/employees/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from employees.forms import EmployeeEditForm, EditPositionForm
from employees.models import Employee, Position
import employees.services.services as sv


def home(request):
    """Каталог сотрудников в древовидной форме"""

    employees = (Employee.objects
                 .select_related('position')
                 .all())

    return render(
        request,
        'employees/home.html',
        {'employees': employees}
    )


def employees_list(request):
    """Список всех сотрудников"""

    options = sv.collect_search_bar_info(request.GET)
    employees = sv.sort_by_field_options(
        sv.get_employees_by_keyword(options.get('keyword')),
        [option for option in options if (options[option] and option != 'keyword')]
    )
    paginator, pages = sv.get_model_paginator(employees, request.GET.get('page', 1), 100)

    return render(
        request,
        'employees/employees_list.html',
        {
            'options': options,
            'employees': paginator,
            'pages': pages
        }
    )


def employee_details(request, employee_slug):
    """
    Данные работника.

    :param employee_slug: `Slug` конкретного работника.
    """

    employee = sv.return_404_if_none(sv.get_by(Employee, {'slug': employee_slug}, ['parent', 'position']))

    return render(
        request,
        'employees/employee_details.html',
        {'employee': employee}
    )


@login_required
def create_employee(request):
    """Создание работника"""

    form = EmployeeEditForm(
        request.POST or None,
        request.FILES or None,
    )

    if form.is_valid():
        employee = sv.save_employee_from_form(form)
        messages.success(request, 'Работник создан')
        return redirect(employee.get_absolute_url())

    return render(
        request,
        'employees/create_employee.html',
        {'form': form}
    )


@login_required
def edit_employee(request, employee_slug):
    """
    Изменение данных сотрудника.

    :param employee_slug: `slug` работника, по которому получается модель.
    """

    form = EmployeeEditForm(
        request.POST or None, request.FILES or None,
        instance=sv.return_404_if_none(sv.get_by(Employee, {'slug': employee_slug}, ['parent', 'position'])),
    )

    if form.is_valid():
        employee = sv.save_employee_from_form(form)
        messages.success(request, 'Данные обновлены')
        return redirect(employee.get_absolute_url())

    return render(
        request,
        'employees/edit_employee.html',
        {
            'form': form,
            'employee_slug': employee_slug,
        }
    )


@login_required
def delete_photo(request, employee_pk):
    """
    Удаляет фото работника.

    :param employee_pk: id экземпляра.
    """

    employee = sv.return_404_if_none(sv.get_by(Employee, {'pk': employee_pk}, ['parent', 'position']))
    sv.delete_employee_photo(employee)

    return redirect(employee.get_absolute_url())


@login_required
def delete_employee(request, employee_pk):
    """
    Удаление экземпляра модели `Employee`.

    :param employee_pk: id экземпляра.
    """

    sv.return_404_if_none(sv.delete_employee(employee_pk))
    messages.success(request, 'Работник был удалён')

    return redirect('employees:home')


def positions_list(request):
    """Показывает все существующие должности"""

    paginator, pages = sv.get_model_paginator(Position, request.GET.get('page', 1), 100)

    return render(
        request,
        'employees/positions_list.html',
        {
            'positions': paginator,
            'pages': pages,
        }
    )


def position_details(request, position_pk):
    """
    Страница должности.

    :param position_pk: `id`, `primary key` записи модели `Position`.
    """

    position = sv.return_404_if_none(sv.get_by(Position, {'pk': position_pk}))

    form = EditPositionForm(request.POST or None, instance=position)

    if form.is_valid():
        position = form.save()
        return redirect(position.get_absolute_url())

    return render(
        request,
        'employees/position_details.html',
        {
            'position': position,
            'form': form,
        }
    )


@login_required
def delete_position(request, position_pk):
    """
    Удаление должности по ключу `position_pk`.

    :param position_pk: `id`, `primary key` записи модели `Position`.
    """

    sv.return_404_if_none(sv.delete_record_by_pk(Position, position_pk))

    messages.success(request, 'Должность была удалена')

    return redirect('employees:home')


@login_required
def create_position(request):
    """Создание должности"""

    form = EditPositionForm(request.POST or None)

    if form.is_valid():
        position = form.save()
        return redirect(position.get_absolute_url())

    return render(
        request,
        'employees/create_position.html',
        {'form': form}
    )

abz_task/employees/templates/employees/create_employee.html
{% extends 'base.html' %}

{% block content %}

<div class="p-5 mt-4 rounded bg-light shadow-sm">
    <div class="row row-cols-1">

        <div class="col">
            <form action="{% url 'employees:create_employee' %}" method="post"
                  enctype="multipart/form-data" novalidate>
                {% csrf_token %}

                <div class="row g-4">

                    <div class="col-lg-4">
                        <div class="d-flex">
                            <span class="fw-bold">Имя:</span>{{ form.first_name }}
                        </div>
                        {% include 'includes/errors.html' with field=form.first_name %}

                    </div>
                    <div class="col-lg-4">
                        <div class="d-flex">
                            <span class="fw-bold">Фамилия:</span>{{ form.second_name }}
                        </div>
                        {% include 'includes/errors.html' with field=form.second_name %}

                    </div>
                    <div class="col-lg-4">
                        <div class="d-flex">
                            <span class="fw-bold">Отчество:</span>{{ form.patronymic }}
                        </div>
                        {% include 'includes/errors.html' with field=form.patronymic %}

                    </div>

                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Дата трудоустройства:</span>
                            <div class="flex-fill pe-2">{{ form.date_employment }}</div>
                        </div>
                        {% include 'includes/errors.html' with field=form.date_employment %}

                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Позиция:</span>
                            {{ form.position }}
                        </div>
                        {% include 'includes/errors.html' with field=form.position %}

                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Начальник:</span>
                            {{ form.parent }}
                        </div>
                        {% include 'includes/errors.html' with field=form.parent %}

                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Зарплата:</span>
                            {{ form.payment }}
                        </div>
                        {% include 'includes/errors.html' with field=form.payment %}
                    </div>
                    <div class="col-lg-4">
                        <div class="">
                            <p class="file-upload">
                                <span class="fw-bold">Фото работника:</span>
                                {{ form.employee_photo }}
                            </p>
                            {% include 'includes/errors.html' with field=form.employee_photo %}
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <input type="submit" value="Сохранить" class="btn btn-primary btn-primary-sm">
                </div>
            </form>
        </div>

    </div>

</div>
{% endblock %}

abz_task/employees/templates/employees/create_position.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5 mt-4 rounded bg-light shadow-sm">
    <div class="row row-cols-1">

        <div class="col">

            <form action="{% url 'employees:create_position' %}" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <div class="row g-4">
                    <div class="col-lg-5">
                        <div class="d-flex">
                            <span class="fw-bold me-2">Название:</span>{{ form.title }}
                        </div>
                        {% include 'includes/errors.html' with field=form.first_name %}
                    </div>
                    <div class="col-lg-7 d-flex justify-content-end">
                        <input type="submit" value="Сохранить" class="btn btn-primary btn-primary-sm">
                    </div>
                </div>
            </form>

        </div>

    </div>

</div>
{% endblock %}

abz_task/employees/templates/employees/edit_employee.html
{% extends 'base.html' %}

{% block content %}

<div class="p-5 mt-4 rounded bg-light shadow-sm">
    <div class="row row-cols-1">

        <div class="col">
            <div class="pb-4">
                <a href="{% url 'employees:employee_details' employee_slug %}" class="link-primary">Обратно</a>
            </div>
        </div>

        <div class="col">
            <form action="{% url 'employees:edit_employee' employee_slug %}" method="post"
                  enctype="multipart/form-data" novalidate>
                {% csrf_token %}

                <div class="row g-4">

                    <div class="col-lg-4">
                        <div class="d-flex">
                            <span class="fw-bold">Имя:</span>{{ form.first_name }}
                        </div>
                        {% include 'includes/errors.html' with field=form.first_name %}

                    </div>
                    <div class="col-lg-4">
                        <div class="d-flex">
                            <span class="fw-bold">Фамилия:</span>{{ form.second_name }}
                        </div>
                        {% include 'includes/errors.html' with field=form.second_name %}

                    </div>
                    <div class="col-lg-4">
                        <div class="d-flex">
                            <span class="fw-bold">Отчество:</span>{{ form.patronymic }}
                        </div>
                        {% include 'includes/errors.html' with field=form.patronymic %}

                    </div>

                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Дата трудоустройства:</span>
                            <div class="flex-fill pe-2">{{ form.date_employment }}</div>
                        </div>
                        {% include 'includes/errors.html' with field=form.date_employment %}

                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Позиция:</span>
                            {{ form.position }}
                        </div>
                        {% include 'includes/errors.html' with field=form.position %}

                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Начальник:</span>
                            {{ form.parent }}
                        </div>
                        {% include 'includes/errors.html' with field=form.parent %}

                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex">
                            <span class="fw-bold">Зарплата:</span>
                            {{ form.payment }}
                        </div>
                        {% include 'includes/errors.html' with field=form.payment %}
                    </div>
                    <div class="col-lg-4">
                        <div class="">
                            <p class="file-upload">
                                <span class="fw-bold">Загрузить новое фото:</span>
                                {{ form.employee_photo }}
                            </p>
                            {% include 'includes/errors.html' with field=form.employee_photo %}
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <input type="submit" value="Сохранить" class="btn btn-primary btn-primary-sm">
                </div>
            </form>
        </div>

    </div>

</div>
{% endblock %}

abz_task/employees/templates/employees/employee_details.html
{% extends 'base.html' %}

{% block content %}

<!-- Модальное окно удаления фотографии работника -->
<div class="modal fade" id="deletePhotoModal" tabindex="-1" aria-labelledby="deletePhotoModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                Вы точно хотите удалить фото?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Закрыть</button>
                <a href="{% url 'employees:delete_photo' employee.pk %}" class="btn btn-danger btn-sm">Удалить</a>
            </div>
        </div>
    </div>
</div>


<!-- Модальное окно удаление работника -->
<div class="modal fade" id="deleteEmployeeModal" tabindex="-1" aria-labelledby="deleteEmployeeModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                Вы точно хотите удалить этого работника?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Закрыть</button>
                <a href="{% url 'employees:delete_employee' employee.pk %}" class="btn btn-danger btn-sm">Удалить</a>
            </div>
        </div>
    </div>
</div>


<div class="p-5 px-4 mt-4 rounded bg-light shadow-sm">
    <div class="row">
        <div class="col-lg-4">
            <img src="{{ employee.employee_photo.url }}" alt="Фото пользователя" class="rounded shadow">
        </div>


        <div class="col-lg-8">
            <div class="row g-3">

                <div class="col-auto">
                    <div class="mb-3 fs-5">
                        <span class="fw-bold">ФИО:</span>
                        <span>{{ employee.second_name}} {{ employee.first_name }} {{ employee.patronymic }}</span>
                    </div>
                    <div>
                        <span class="fw-bold">Начальник:</span>
                        {% if employee.parent %}
                        <a href="{{ employee.parent.get_absolute_url }}" class="text-decoration-none"><span>{{ employee.parent }}</span></a>
                        {% else %}
                        <span>-</span>
                        {% endif %}
                    </div>
                    <div>
                        <span class="fw-bold">Должность:</span>
                        <span>
                            {% if employee.position %}
                            <a href="{{ employee.position.get_absolute_url }}" class="link-primary text-decoration-none">
                                {{ employee.position }}
                            </a>
                            {% else %}
                                -
                            {% endif %}
                        </span>
                    </div>
                    <div>
                        <span class="fw-bold">Дата трудоустройства:</span>
                        <span>
                            {{ employee.date_employment|date:"G:H:s," }}
                            {{ employee.date_employment|date:"F j, o" }}
                            </span>
                    </div>
                    <div>
                        <span class="fw-bold">Зарплата:</span>
                        <span>${{ employee.payment }}</span>
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                <div class="col-12">
                    <input type="button" value="Удалить работника" class="btn btn-outline-danger btn-outline-danger-sm" data-bs-toggle="modal" data-bs-target="#deleteEmployeeModal">
                    <a href="{% url 'employees:edit_employee' employee.slug %}" class="btn btn-primary">Изменить</a>
                    {% if employee.employee_photo != default_employee_image %}
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                            data-bs-target="#deletePhotoModal">
                        Удалить фото
                    </button>
                    {% endif %}
                </div>
                {% endif %}

            </div>
        </div>
    </div>


</div>
{% endblock %}

abz_task/employees/templates/employees/employees_list.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/search_bar.html' with options=options %}

{% if employees %}
<div class="mt-4">
    <table class="table table-light table-striped shadow-sm">
        <thead>
        <tr>
            <th scope="col">Фамилия</th>
            <th scope="col">Имя</th>
            <th scope="col">Отчество</th>
            <th scope="col">Фото</th>
            <th scope="col">Должность</th>
            <th scope="col">Зарплата</th>
            <th scope="col">Дата приема на работу</th>
            <th scope="col">Начальник</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
        <tr>
            <td class="align-middle">
                <a href="{{ employee.get_absolute_url }}" class="text-decoration-none">{{ employee.second_name}}</a>
            </td>
            <td class="align-middle">
                <a href="{{ employee.get_absolute_url }}" class="text-decoration-none">{{ employee.first_name }}</a>
            </td>
            <td class="align-middle">
                <a href="{{ employee.get_absolute_url }}" class="text-decoration-none">{{ employee.patronymic }}</a>
            </td>
            <td class="align-middle"><img src="{{ employee.employee_photo.url }}" alt=""
                                          style="height: 36px; border-radius: 18px;"></td>
            <td class="align-middle">
                {% if employee.position %}{{ employee.position }}{% else %}-{% endif %}
            </td>
            <td class="align-middle">${{ employee.payment }}</td>
            <td class="align-middle">
                {{ employee.date_employment|date:"F j, o" }}
                <br>
                <small>{{ employee.date_employment|date:"G:H:s" }}</small>
            </td>
            <td class="align-middle">
                {% if employee.parent %}
                <a href="{{ employee.parent.get_absolute_url }}">{{employee.parent }}</a>
                {% else %}
                -
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="p-4 mt-4 rounded bg-light shadow-sm">
    <small class="text-secondary">Здесь пока ничего нет</small>
</div>
{% endif %}

<div class="mt-4">
    {% include 'includes/pagination.html' with paginator=employees pages=pages params=options %}
</div>

{% endblock %}

abz_task/employees/templates/employees/position_details.html
{% extends 'base.html' %}

{% block content %}

<!-- Модальное окно удаление должности -->
<div class="modal fade" id="deletePositionModal" tabindex="-1" aria-labelledby="deletePositionModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                Вы точно хотите удалить эту категорию?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Закрыть</button>
                <a href="{% url 'employees:delete_position' position.pk %}" class="btn btn-danger btn-sm">Удалить</a>
            </div>
        </div>
    </div>
</div>

<!-- Модальное окно изменение названия должности -->
<div class="modal fade" id="EditEmployeeModal" tabindex="-1" aria-labelledby="EditEmployeeModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form action="{{ position.get_absolute_rul }}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <p>Введите новое название должности:</p>
                    {{ form.title }}
                    {% include 'includes/errors.html' with field=form.title %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Закрыть</button>
                    <input type="submit" class="btn btn-primary btn-sm" value="Сохранить">
                </div>
            </form>
        </div>
    </div>
</div>


<div class="p-5 px-4 mt-4 rounded bg-light shadow-sm">
    <div class="row">

        <div class="col">
            <div class="row g-3">

                <div class="col-auto">
                    <div class="mb-3 fs-5">
                        <span class="fw-bold">Название:</span>
                        <span>{{ position.title }}</span>
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                    <div class="col-12">
                        <input type="button" value="Удалить категорию" class="btn btn-outline-danger btn-outline-danger-sm"
                               data-bs-toggle="modal" data-bs-target="#deletePositionModal">
                        <input type="button" value="Изменить название" class="btn btn-primary btn-outline-danger-sm"
                               data-bs-toggle="modal" data-bs-target="#EditEmployeeModal">
                    </div>
                {% endif %}

            </div>
        </div>
    </div>


</div>
{% endblock %}

abz_task/employees/templates/employees/positions_list.html
{% extends 'base.html' %}

{% block content %}

{% if positions %}
<div class="mt-4">
    <table class="table table-light table-striped shadow-sm">
        <thead>
        <tr>
            <th scope="col">Название</th>
        </tr>
        </thead>
        <tbody>
        {% for position in positions %}
        <tr>
            <td class="align-middle">
                <a href="{{ position.get_absolute_url }}" class="text-decoration-none">{{ position.title }}</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class="p-4 mt-4 rounded bg-light shadow-sm">
    <small class="text-secondary">Здесь пока ничего нет</small>
</div>
{% endif %}

<div class="mt-4">
    {% include 'includes/pagination.html' with paginator=positions current_page=positions.number %}
</div>

{% endblock %}