abz_task/abz_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

abz_task/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

from .views import CustomLoginView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

abz_task/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.home, name='home'),
    path('employees_list/', views.employees_list, name='employees_list'),
    path('employee/<slug:employee_slug>/', views.employee_details, name='employee_details'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('edit_employee/<slug:employee_slug>/', views.edit_employee, name='edit_employee'),
    path('delete_photo/<int:employee_pk>/', views.delete_photo, name='delete_photo'),
    path('delete_employee/<int:employee_pk>/', views.delete_employee, name='delete_employee'),
    path('positions_list/', views.positions_list, name='positions_list'),
    path('position_details/<int:position_pk>/', views.position_details, name='position_details'),
    path('delete_position/<int:position_pk>/', views.delete_position, name='delete_position'),
    path('create_position/', views.create_position, name='create_position'),
]

abz_task/templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        </div>
    {% endfor %}

{% endif %}

abz_task/templates/includes/errors.html
{% if field.errors %}
    {% for error in field.errors %}
        <small class="text-danger">{{ error }}</small><br>
    {% endfor %}
{% endif %}

abz_task/templates/includes/navbar.html
<section>
    <div class="container">
        <div class="rounded bg-light mt-4 p-4 shadow-sm">

            <div class="row g-2">

                <div class="col-lg-auto col-12">
                    <a href="{% url 'employees:home' %}" class="link-primary text-decoration-none">Главная страница</a></div>
                <div class="col-lg-auto">
                    <span class="d-lg-flex d-none fw-light">|</span>
                </div>
                <div class="col-lg-auto col-12">
                    <a href="{% url 'employees:employees_list' %}" class="link-primary text-decoration-none">Список сотрудников</a>
                </div>
                <div class="col-lg-auto">
                    <span class="d-lg-flex d-none fw-light">|</span>
                </div>
                <div class="col-lg-auto col-12">
                    <a href="{% url 'employees:positions_list' %}" class="link-primary text-decoration-none">Список должностей</a>
                </div>

                <div class="col"></div>

                <div class="col-lg-auto col-12">
                    <div class="d-flex">
                        {% if request.user.is_authenticated %}
                            <span>{{ request.user }}</span>
                            <span class="mx-2 fw-light">|</span>
                            <a href="{% url 'accounts:logout' %}" class="link-dark text-decoration-none"><i class="bi bi-box-arrow-left me-1"></i>Выйти</a>
                        {% else %}
                            <a href="{% url 'accounts:login' %}" class="link-dark"><i class="bi bi-box-arrow-in-right me-1"></i>Войти</a>
                            <span class="mx-2 fw-light">|</span>
                            <a href="{% url 'accounts:register' %}" class="link-dark"><i class="bi bi-person-plus me-1"></i>Создать аккаунт</a>
                        {% endif %}
                    </div>
                </div>

            </div>

            {% if request.user.is_authenticated %}
            <div class="mt-2">
                <div class="row g-2">
                    <div class="col-lg-auto col-12">
                        <a href="{% url 'employees:create_employee' %}" class="link-primary text-decoration-none">Добавить работника</a>
                    </div>
                    <div class="col-lg-auto">
                        <span class="d-lg-flex d-none fw-light">|</span>
                    </div>
                    <div class="col-lg-auto col-12">
                        <a href="{% url 'employees:create_position' %}" class="link-primary text-decoration-none">Добавить должность</a></div>
                    <div class="col"></div>
                </div>
            </div>
            {% endif %}

        </div>
    </div>
</section>

abz_task/templates/includes/pagination.html
{% load pagination_tags %}

{% if paginator.paginator.num_pages > 1 %}

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            {% if paginator.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url_parameters params page=paginator.previous_page_number %}">Previous</a>
                </li>
            {% endif %}

            {% for page in pages %}
                <li class="page-item {% if paginator.number == page %}active{% endif %}">
                    <a class="page-link" href="{% if page|is_int %}{% url_parameters params page=page %}{% endif %}">{{ page }}</a>
                </li>
            {% endfor %}

            {% if paginator.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url_parameters params page=paginator.next_page_number %}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>

{% endif %}

abz_task/templates/includes/search_bar.html
<section>
    <div class="p-4 mt-4 rounded bg-light shadow-sm">
        <form action="{% url 'employees:employees_list' %}" method="get">
            <div class="row g-2">

                <div class="col-lg-3 col">
                    <input type="text" class="form-control form-control-sm shadow-sm" placeholder="Поиск"
                           name="keyword" value="{{ options.keyword }}">
                </div>

                <div class="col-auto">
                    <button type="submit" class="btn btn-outline-primary btn-sm"><small></small>Искать</button>
                </div>

                <div class="col-12">
                    <div class="rounded border bg-white p-2 mt-2 shadow-sm">
                        <h5 class="fs-6">Сортировать по:</h5>

                        <div class="row text-secondary g-3">
                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input me-1" placeholder="Поиск"
                                       name="first_name" {% if options.first_name %} checked {% endif %}>
                                <small>Имя</small>
                            </div>

                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input " placeholder="Поиск" name="second_name" {% if options.second_name %} checked {% endif %}>
                                <small>Фамилия</small>
                            </div>

                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input " placeholder="Поиск" name="patronymic" {% if options.patronymic %} checked {% endif %}>
                                <small>Отчество</small>
                            </div>

                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input " placeholder="Поиск" name="position__title" {% if options.position__title %} checked {% endif %}>
                                <small>Должность</small>
                            </div>

                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input " placeholder="Поиск" name="payment" {% if options.payment %} checked {% endif %}>
                                <small>Зарплата</small>
                            </div>

                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input " placeholder="Поиск" name="parent__second_name" {% if options.parent__second_name %} checked {% endif %}>
                                <small>Начальник</small>
                            </div>

                            <div class="col-auto">
                                <input type="checkbox" class="form-check-input " placeholder="Поиск"
                                       name="date_employment" {% if options.date_employment %} checked {% endif %}>
                                <small>Дата приема на работу</small>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</section>